services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pwd
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    build:
    ports:
      - "9091:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres_user:postgres_pwd@db/postgres

volumes:
  postgres_data:
